#version 450
#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

#include "layout.glsl"
#include "material.glsl"

BLASHit intersect(Ray ray, uint rootNode, uint baseTri, float eps) {
    BLASHit closestHit = BLASHit(UINT_MAX, FLT_MAX, 0, 0);
    uint stack[16];
    uint sp = 0;
    stack[sp++] = rootNode;
    while (sp != 0) {
        uint nodeIdx = stack[--sp];
        Node node = nodeBuffer.data[nodeIdx];
        float tNode = intersect(node.bbox, ray);
        if (tNode == FLT_MAX || tNode >= closestHit.t) continue;
        uint primCount = primCount(node.index);
        if (primCount != 0) {
            uint id = baseTri + id(node.index);
            for (uint i = 0; i < primCount; ++i) {
                PrecomputedTriangle tri = triangleBuffer.data[id + i];
                TriHit triHit = intersect(tri, ray, eps);
                if (triHit.t > eps && triHit.t < closestHit.t) {
                    closestHit = BLASHit(id + i, triHit.t, triHit.u, triHit.v);
                }
            }
        } else {
            uint leftIdx  = rootNode + id(node.index);
            uint rightIdx = leftIdx + 1;
            Node left  = nodeBuffer.data[leftIdx];
            Node right = nodeBuffer.data[rightIdx];
            float tLeft  = intersect(left.bbox, ray);
            float tRight = intersect(right.bbox, ray);
            bool hitLeft  = (tLeft  != FLT_MAX) && (tLeft  < closestHit.t);
            bool hitRight = (tRight != FLT_MAX) && (tRight < closestHit.t);
            if (hitLeft && hitRight) {
                if (tLeft < tRight) {
                    stack[sp++] = rightIdx;
                    stack[sp++] = leftIdx;
                } else {
                    stack[sp++] = leftIdx;
                    stack[sp++] = rightIdx;
                }
            } else if (hitLeft) {
                stack[sp++] = leftIdx;
            } else if (hitRight) {
                stack[sp++] = rightIdx;
            }
        }
    }
    return closestHit;
}

//Hit intersect(Ray ray, float eps) {
//    Hit closestHit = Hit(UINT_MAX, UINT_MAX, FLT_MAX, 0, 0);
//    for (int i = 0; i < pc.instanceCount; ++i) {
//        Instance instance = instanceBuffer.data[i];
//
//        vec3 localPos = vec3(instance.invModel * vec4(ray.pos, 1.0));
//        vec3 localDir = normalize(vec3(instance.invModel * vec4(ray.dir, 0.0)));
//        Ray localRay = makeRay(localPos, localDir, 0.0, FLT_MAX);
//
//        BLASHit instanceHit = intersect(localRay, instance.baseNode, instance.baseTri, eps);
//
//        if (instanceHit.t > eps && instanceHit.t < closestHit.t) {
//            closestHit = Hit(instanceHit.id, i, instanceHit.t, instanceHit.u, instanceHit.v);
//        }
//    }
//    return closestHit;
//}

Hit intersect(Ray ray, float eps) {
    Hit closestHit = Hit(UINT_MAX, UINT_MAX, FLT_MAX, 0, 0);
    uint stack[16];
    uint sp = 0;
    stack[sp++] = 0;
    while (sp != 0) {
        uint nodeIdx = stack[--sp];
        Node node = TLASNodeBuffer.data[nodeIdx];
        float tNode = intersect(node.bbox, ray);
        if (tNode == FLT_MAX || tNode >= closestHit.t) continue;
        uint primCount = primCount(node.index);
        if (primCount != 0) {
            uint id = id(node.index);
            for (uint i = 0; i < primCount; ++i) {
                Instance instance = instanceBuffer.data[id + i];
                vec3 localPos = vec3(instance.invModel * vec4(ray.pos, 1.0));
                vec3 localDir = normalize(vec3(instance.invModel * vec4(ray.dir, 0.0)));
                Ray localRay = makeRay(localPos, localDir, 0.0, FLT_MAX);
                BLASHit instanceHit = intersect(localRay, instance.baseNode, instance.baseTri, eps);
                if (instanceHit.t > eps && instanceHit.t < closestHit.t) {
                    closestHit = Hit(instanceHit.id, id + i, instanceHit.t, instanceHit.u, instanceHit.v);
                }
            }
        } else {
            uint leftIdx  = id(node.index);
            uint rightIdx = leftIdx + 1;
            Node left  = TLASNodeBuffer.data[leftIdx];
            Node right = TLASNodeBuffer.data[rightIdx];
            float tLeft  = intersect(left.bbox, ray);
            float tRight = intersect(right.bbox, ray);
            bool hitLeft  = (tLeft  != FLT_MAX) && (tLeft  < closestHit.t);
            bool hitRight = (tRight != FLT_MAX) && (tRight < closestHit.t);
            if (hitLeft && hitRight) {
                if (tLeft < tRight) {
                    stack[sp++] = rightIdx;
                    stack[sp++] = leftIdx;
                } else {
                    stack[sp++] = leftIdx;
                    stack[sp++] = rightIdx;
                }
            } else if (hitLeft) {
                stack[sp++] = leftIdx;
            } else if (hitRight) {
                stack[sp++] = rightIdx;
            }
        }
    }
    return closestHit;
}

#define skyColor vec3(0)

float getShadow(vec3 P, vec3 dir) {
    Ray shadowRay = makeRay(P, dir, 0.0, FLT_MAX);
    Hit shadowHit = intersect(shadowRay, 1e-6);

    if (shadowHit.triId == UINT_MAX) return 1;
    return 0;
}

vec3 traceRay(uint seed, vec3 albedo, float depth, vec3 P, vec3 N) {
    if (depth >= 1.0) { ;
        return skyColor;
    }
    vec3 resultColor = vec3(0.0);
    vec3 throughput  = vec3(1.0);

    //vec3 wo = -rayDir;
    vec3 L  = -directLight.dir.xyz;
    Scatter scatter = lambertianScatter(seed, albedo, N, vec3(1));

    float cosTheta   = max(dot(N, L), 0.0);
    vec3  movedP     = P + N * 0.1;
    vec3  directColor = scatter.brdf * cosTheta * directLight.intensity * getShadow(movedP, L);
    resultColor += directColor;
    throughput  *= scatter.brdf * dot(N, scatter.wi) / scatter.pdf;
    Ray currentRay = makeRay(movedP, scatter.wi, 0.0, FLT_MAX);

    for (uint depth = 1; depth < pc.maxDepth; ++depth) {
        Hit hit = intersect(currentRay, 1e-3);
        if (hit.triId == UINT_MAX) {
            resultColor += throughput * skyColor;
            break;
        }
        PrecomputedTriangle tri = triangleBuffer.data[hit.triId];
        TriangleExtra triExtra = triangleExtraBuffer.data[hit.triId];
        Instance instance = instanceBuffer.data[hit.instanceId];
        vec3 localP = vec3(tri.p0 + hit.u * tri.e1 + hit.v * tri.e2);
        vec3 P = vec3(instance.model * vec4(localP, 1.0));
        vec2 uv = getUV(triExtra, hit.u, hit.v);
        vec3 albedo = texture(textures[nonuniformEXT(triExtra.texIndex)], uv).rgb;
        vec3 L = -directLight.dir.xyz;
        vec3 N = normalize(tri.N.xyz);
        N = faceforward(N, currentRay.dir, N);
        vec3 wo = -currentRay.dir;
        Scatter scatter = lambertianScatter(seed, albedo, N, wo);
        float cosTheta = max(dot(N,L), 0);
        vec3 movedP = P + N * 0.1;
        vec3 directColor = scatter.brdf * cosTheta * directLight.intensity * getShadow(movedP, L);
        resultColor += throughput * directColor;
        throughput *= scatter.brdf * dot(N, scatter.wi) / scatter.pdf;
        if (depth >= pc.minDepth) {
            float p = max(throughput.r, max(throughput.g, throughput.b));
            p = clamp(p, 0.05, 1.0);
            if (rand01(seed) > p) break;
            throughput /= p;
        }
        currentRay = makeRay(movedP, scatter.wi, 0.0, FLT_MAX);
    }
    return resultColor;
}

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    vec2 wh = imageSize(outputImage);
    vec2 uv = coord / wh;
    float depth = texture(depthImage, uv).r;
    vec2 ndc = uv * 2.0 - 1.0;
    vec4 clip = vec4(ndc, depth, 1.0);
    vec4 world = camera.invViewProj * clip;
    world /= world.w;

    vec3 albedo = texture(colorImage, uv).rgb;
    vec3 P = world.xyz;
    vec3 N = texture(normalImage, uv).rgb;
    vec3 tracedColor = vec3(0.0);
    for (uint i = 0; i < pc.spp; i++) {
        uint seed = coord.x + coord.y * 1973u + pc.frame * 9277u + i * 26699u;
        tracedColor += traceRay(seed, albedo, depth, P, N);
    }
    tracedColor /= float(pc.spp);

    if (pc.frame == 0) {
        imageStore(outputImage, coord, vec4(tracedColor, 1.0));
        return;
    }
    vec3 imageColor = imageLoad(outputImage, coord).rgb;
    vec3 newColor = (imageColor * pc.frame + tracedColor) / (pc.frame + 1);
    imageStore(outputImage, coord, vec4(newColor, 1.0));
}