#version 450
#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

#include "layout.glsl"
#include "material.glsl"

#define skyColor vec3(0.2)

float getShadow(vec3 P, vec3 dir) {
    Ray shadowRay = makeRay(P, dir, 0.0, FLT_MAX);
    Hit shadowHit = intersect(shadowRay, 1e-6);

    if (shadowHit.triId == UINT_MAX) return 1;
    return 0;
}

float offsetBias(vec3 P) {
    return max(length(P - camera.pos.xyz) * 1e-3, 1e-2);
}

vec3 traceRay(uint seed, vec3 albedo, float inDepth, vec3 P, vec3 N) {
    if (inDepth >= 1.0) { ;
        return skyColor;
    }
    vec3 resultColor = vec3(0.0);
    vec3 throughput  = vec3(1.0);

    //vec3 wo = -rayDir;
    vec3 L  = -directLight.dir.xyz;
    Scatter scatter = lambertianScatter(seed, albedo, N, vec3(1));

    float cosTheta   = max(dot(N, L), 0.0);
    vec3  movedP     = P + N * offsetBias(P);
    vec3  directColor = scatter.brdf * cosTheta * directLight.intensity * getShadow(movedP, L);
    resultColor += directColor;
    throughput  *= scatter.brdf * dot(N, scatter.wi) / scatter.pdf;
    Ray currentRay = makeRay(movedP, scatter.wi, 0.0, FLT_MAX);

    for (uint depth = 1; depth < pc.maxDepth; ++depth) {
        Hit hit = intersect(currentRay, 1e-3);
        if (hit.triId == UINT_MAX) {
            resultColor += throughput * skyColor;
            break;
        }
        if (depth >= pc.minDepth) {
            float p = clamp(luminance(throughput), 0.01, 1.0);
            if (rand01(seed) > p) break;
            throughput /= p;
        }
        PrecomputedTriangle tri = triangleBuffer.data[hit.triId];
        TriangleExtra triExtra = triangleExtraBuffer.data[hit.triId];
        Instance instance = instanceBuffer.data[hit.instanceId];
        vec3 localP = vec3(tri.p0 + hit.u * tri.e1 + hit.v * tri.e2);
        vec3 P = vec3(instance.model * vec4(localP, 1.0));
        vec2 uv = getUV(triExtra, hit.u, hit.v);
        vec3 albedo = textureLod(textures[nonuniformEXT(instance.texIndex)], uv, 0).rgb;
        vec3 L = -directLight.dir.xyz;
        vec3 N = normalize(mat3(transpose(instance.invModel)) * tri.N.xyz);
        N = faceforward(N, currentRay.dir, N);
        vec3 wo = -currentRay.dir;
        Scatter scatter = lambertianScatter(seed, albedo, N, wo);
        float cosTheta = max(dot(N,L), 0);
        vec3 movedP = P + N * offsetBias(P);
        vec3 directColor = scatter.brdf * cosTheta * directLight.intensity * getShadow(movedP, L);
        resultColor += throughput * directColor;
        throughput *= scatter.brdf * dot(N, scatter.wi) / scatter.pdf;
        currentRay = makeRay(movedP, scatter.wi, 0.0, FLT_MAX);
    }
    return resultColor;
}

vec3 tracedAlbedo() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    vec2 wh = imageSize(outputImage);
    vec2 uv = coord / wh;
    float depth = texture(depthImage, uv).r;
    vec2 ndc = uv * 2.0 - 1.0;
    vec4 clip = vec4(ndc, depth, 1.0);
    vec4 world = camera.invViewProj * clip;
    world /= world.w;

    vec3 rayOrigin = camera.pos.xyz;
    vec3 rayDir = normalize(world.xyz - rayOrigin);
    Ray currentRay = makeRay(rayOrigin, rayDir, 0.0, FLT_MAX);
    Hit hit = intersect(currentRay, 1e-6);
    if (hit.triId == UINT_MAX) {
        return skyColor;
    }
    PrecomputedTriangle tri = triangleBuffer.data[hit.triId];
    TriangleExtra triExtra = triangleExtraBuffer.data[hit.triId];
    Instance instance = instanceBuffer.data[hit.instanceId];
    vec3 localP = vec3(tri.p0 + hit.u * tri.e1 + hit.v * tri.e2);
    vec3 P = vec3(instance.model * vec4(localP, 1.0));
    vec3 albedo = texture(textures[nonuniformEXT(instance.texIndex)], getUV(triExtra, hit.u, hit.v)).rgb;
    return albedo;
}

vec3 tracedColor() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    vec2 wh = imageSize(outputImage);
    vec2 uv = coord / wh;
    float depth = texture(depthImage, uv).r;
    vec2 ndc = uv * 2.0 - 1.0;
    vec4 clip = vec4(ndc, depth, 1.0);
    vec4 world = camera.invViewProj * clip;
    world /= world.w;

    vec3 albedo = texture(colorImage, uv).rgb;
    vec3 P = world.xyz;
    vec3 N = texture(normalImage, uv).rgb;
    N = faceforward(N, P - camera.pos.xyz, N);
    vec3 color = vec3(0.0);
    for (uint i = 0; i < pc.spp; i++) {
        uint seed = coord.x + coord.y * 1973u + pc.frame * 9277u + i * 26699u;
        color += traceRay(seed, albedo, depth, P, N);
    }
    color /= float(pc.spp);
    return color;
}

vec3 depthColor() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    vec2 wh = imageSize(outputImage);
    vec2 uv = coord / wh;
    float depth = texture(depthImage, uv).r;
    float near = 0.1;
    float far  = 100.0;
    float linearDepth = (2.0 * near * far) / (far + near - (depth * 2.0 - 1.0) * (far - near));
    return vec3(linearDepth / far);
}

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    vec2 wh = imageSize(outputImage);
    vec2 uv = coord / wh;
    vec3 outColor = vec3(0.0);
    switch (pc.displayMode) {
        case 0: outColor = texture(colorImage, uv).rgb; break;
        case 1: outColor = depthColor(); break;
        case 2: outColor = texture(normalImage, uv).rgb * 0.5 + 0.5; break;
        case 3: outColor = tracedAlbedo(); break;
        case 4: outColor = tracedColor(); break;
    }
    if (pc.frame == 0) {
        imageStore(outputImage, coord, vec4(outColor, 1.0));
        return;
    }
    vec3 imageColor = imageLoad(outputImage, coord).rgb;
    vec3 newColor = (imageColor * pc.frame + outColor) / (pc.frame + 1);
    imageStore(outputImage, coord, vec4(newColor, 1.0));
}
