#version 450
#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

#define TEXTURE_NUM 5

#include "layout.glsl"
#include "material.glsl"

//__device__ void traverseIterative( CollisionList& list,
//                                   BVH& bvh,
//                                   AABB& queryAABB,
//                                   int queryObjectIdx)
//{
//    // Allocate traversal stack from thread-local memory,
//    // and push NULL to indicate that there are no postponed nodes.
//    NodePtr stack[64];
//    NodePtr* stackPtr = stack;
//    *stackPtr++ = NULL; // push
//
//    // Traverse nodes starting from the root.
//    NodePtr node = bvh.getRoot();
//    do
//    {
//        // Check each child node for overlap.
//        NodePtr childL = bvh.getLeftChild(node);
//        NodePtr childR = bvh.getRightChild(node);
//        bool overlapL = ( checkOverlap(queryAABB,
//                                       bvh.getAABB(childL)) );
//        bool overlapR = ( checkOverlap(queryAABB,
//                                       bvh.getAABB(childR)) );
//
//        // Query overlaps a leaf node => report collision.
//        if (overlapL && bvh.isLeaf(childL))
//            list.add(queryObjectIdx, bvh.getObjectIdx(childL));
//
//        if (overlapR && bvh.isLeaf(childR))
//            list.add(queryObjectIdx, bvh.getObjectIdx(childR));
//
//        // Query overlaps an internal node => traverse.
//        bool traverseL = (overlapL && !bvh.isLeaf(childL));
//        bool traverseR = (overlapR && !bvh.isLeaf(childR));
//
//        if (!traverseL && !traverseR)
//            node = *--stackPtr; // pop
//        else
//        {
//            node = (traverseL) ? childL : childR;
//            if (traverseL && traverseR)
//                *stackPtr++ = childR; // push
//        }
//    }
//    while (node != NULL);
//}

Hit intersectLeafs(Ray ray, float eps, const uint id, const uint primCount, Hit closestHit) {
    for (uint i = 0; i < primCount; ++i) {
        PrecomputedTriangle tri = triangleBuffer.data[id + i];
        TriHit triHit = intersect(tri, ray, eps);
        if (triHit.t > eps && triHit.t < closestHit.t) {
            closestHit = Hit(id + i, triHit.t, triHit.u, triHit.v);
        }
    }
    return closestHit;
}

Hit intersect(Ray ray, float eps) {
    Hit closestHit = Hit(UINT_MAX, FLT_MAX, 0, 0);
    uint stack[16];
    uint sp = 0;
    stack[sp++] = 0;
    while (sp != 0) {
        uint nodeIdx = stack[--sp];
        Node node = nodeBuffer.data[nodeIdx];
        float tNode = intersect(node.bbox, ray);
        if (tNode == FLT_MAX || tNode >= closestHit.t) continue;
        uint primCount = primCount(node.index);
        if (primCount != 0) {
            uint id = id(node.index);
            for (uint i = 0; i < primCount; ++i) {
                PrecomputedTriangle tri = triangleBuffer.data[id + i];
                TriHit triHit = intersect(tri, ray, eps);
                if (triHit.t > eps && triHit.t < closestHit.t) {
                    closestHit = Hit(id + i, triHit.t, triHit.u, triHit.v);
                }
            }
        } else {
            uint leftIdx  = id(node.index);
            uint rightIdx = leftIdx + 1;
            Node left  = nodeBuffer.data[leftIdx];
            Node right = nodeBuffer.data[rightIdx];
            float tLeft  = intersect(left.bbox, ray);
            float tRight = intersect(right.bbox, ray);
            bool hitLeft  = (tLeft  != FLT_MAX) && (tLeft  < closestHit.t);
            bool hitRight = (tRight != FLT_MAX) && (tRight < closestHit.t);
            if (hitLeft && hitRight) {
                if (tLeft < tRight) {
                    stack[sp++] = rightIdx;
                    stack[sp++] = leftIdx;
                } else {
                    stack[sp++] = leftIdx;
                    stack[sp++] = rightIdx;
                }
            } else if (hitLeft) {
                stack[sp++] = leftIdx;
            } else if (hitRight) {
                stack[sp++] = rightIdx;
            }
        }
    }

    return closestHit;
}

#define skyColor vec3(0)

float getShadow(vec3 P, vec3 dir) {
    Ray shadowRay = makeRay(P, dir, 0.0, FLT_MAX);
    Hit shadowHit = intersect(shadowRay, 1e-6);

    if (shadowHit.id == UINT_MAX) return 1;
    return 0;
}

vec3 traceRay(Ray ray) {
    uint seed = uint(gl_GlobalInvocationID.x) + uint(gl_GlobalInvocationID.y) * 1973u + pc.frame * 9277u;
    vec3 resultColor = vec3(0.0);
    vec3 throughput = vec3(1.0);
    Ray currentRay = ray;
    for (uint depth = 0; depth < pc.maxDepth; ++depth) {
        Hit hit = intersect(currentRay, 1e-6);
        if (hit.id == UINT_MAX) {
            resultColor += throughput * skyColor;
            break;
        }
        PrecomputedTriangle tri = triangleBuffer.data[hit.id];
        TriangleExtra triExtra = triangleExtraBuffer.data[hit.id];
        vec2 uv = getUV(triExtra, hit.u, hit.v);
        vec3 albedo = texture(textures[nonuniformEXT(materialIndexBuffer.data[hit.id] * TEXTURE_NUM)], uv).rgb;
        vec3 P = currentRay.pos + currentRay.dir * hit.t;
        vec3 L = -directLight.dir.xyz;
        vec3 N = normalize(tri.N.xyz);
        N = faceforward(N, currentRay.dir, N);
        vec3 wo = -currentRay.dir;
        Scatter scatter = lambertianScatter(seed, albedo, N, wo);
        float cosTheta = max(dot(N,L), 0);
        vec3 movedP = P + N * 1e-3;
        vec3 directColor = scatter.brdf * cosTheta * directLight.intensity * getShadow(movedP, L);
        resultColor += throughput * directColor;
        throughput *= scatter.brdf * dot(N, scatter.wi) / scatter.pdf;
//        if (depth >= 3) {
//            float p = max(throughput.r, max(throughput.g, throughput.b));
//            p = clamp(p, 0.05, 1.0);
//            if (rand01(seed) > p) break;
//            throughput /= p;
//        }
        currentRay = makeRay(movedP, scatter.wi, 0.0, FLT_MAX);
    }
    return resultColor;
}

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    const float imagePlaneHeight = 2.0 * tan(radians(camera.FOV * 0.5));
    const float imagePlaneWidth  = imagePlaneHeight * camera.aspectRatio;

    const float u  = (coord.x + 0.5) / pc.width;
    const float px = (2.0 * u - 1.0) * imagePlaneWidth * 0.5;
    const float v  = (coord.y + 0.5) / pc.height;
    const float py = (2.0 * v - 1.0) * imagePlaneHeight * 0.5;
    vec3 dir = normalize(px * vec3(camera.right) + py * vec3(camera.up) + vec3(camera.forward));
    Ray ray = makeRay(vec3(camera.position), dir, camera.nearPlane, camera.farPlane);
    vec3 tracedColor = traceRay(ray);
    if (pc.frame == 0) {
        imageStore(image, coord, vec4(tracedColor, 1.0));
        return;
    }
    vec3 imageColor = imageLoad(image, coord).rgb;
    vec3 newColor = (imageColor * pc.frame + tracedColor) / (pc.frame + 1);
    imageStore(image, coord, vec4(newColor, 1.0));
}