#version 460
#extension GL_EXT_ray_tracing : require

#include "utils.glsl"

layout(binding = 0) uniform accelerationStructureEXT tlas;
layout(binding = 1, rgba16f) uniform image2D outputImage;
layout(set = 0, binding = 2) uniform Camera {
    mat4 invView;
    mat4 invProj;
} camera;

layout(location = 0) rayPayloadEXT vec3 payload;

void main() {
    ivec2 pixel = ivec2(gl_LaunchIDEXT.xy);
    vec2 size = vec2(gl_LaunchSizeEXT.xy);
    vec2 uv = (vec2(gl_LaunchIDEXT.xy) + 0.5) /
    vec2(gl_LaunchSizeEXT.xy);
    uv = uv * 2.0 - 1.0;
    vec4 target =
    camera.invProj * vec4(uv, 1.0, 1.0);
    target /= target.w;
    vec3 direction = normalize((camera.invView * vec4(target.xyz, 0.0)).xyz);
    vec3 origin = (camera.invView * vec4(0.0, 0.0, 0.0, 1.0)).xyz;
    payload = vec3(0.0);

    traceRayEXT(
        tlas,
        gl_RayFlagsOpaqueEXT,
        ALL_OBJECTS,
        0, 0, 0,
        origin,
        T_MIN,
        direction,
        T_MAX,
        0
    );

    imageStore(outputImage, pixel, vec4(payload, 1.0));
}