#version 450
#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

#define TEXTURE_NUM 5
#define PRIM_COUNT_BITS 4

struct PrecomputedTriangle {
    vec4 p0, e1, e2, N;
};

struct TriangleExtra {
    vec2 uv0, uv1, uv2;
    vec2 padding;
};

struct BBox {
    vec4 min, max;
};

struct Node {
    BBox bbox;
    uint index;
    uint pad[3];
};

layout(push_constant) uniform PushConstants {
    int width, height;
} pc;

layout(binding = 0) uniform Camera {
    vec4 position, forward, right, up;
    float FOV, aspectRatio, nearPlane, farPlane;
} camera;

layout(binding = 1) buffer TriangleBuffer {
    PrecomputedTriangle data[];
} triangleBuffer;

layout(binding = 2) buffer TriangleExtraBuffer {
    TriangleExtra data[];
} triangleExtraBuffer;

layout(binding = 3) buffer NodeBuffer {
    Node data[];
} nodeBuffer;

layout(binding = 4, rgba8) uniform writeonly image2D outImage;

layout(binding = 5) buffer MaterialIndexBuffer {
    uint data[];
} materialIndexBuffer;

layout(binding = 6) uniform sampler2D textures[];

struct Ray {
    vec3 pos, dir, invDir;
    float tmin, tmax;
};

const uint MAX_PRIM = (1u << PRIM_COUNT_BITS) - 1u;

uint id(uint index) {
    return index >> PRIM_COUNT_BITS;
}

uint primCount(uint index) {
    return index & MAX_PRIM;
}

Ray makeRay(vec3 pos, vec3 dir, float tmin, float tmax) {
    Ray ray;
    ray.pos = pos;
    ray.dir = dir;
    ray.tmin = tmin;
    ray.tmax = tmax;
    ray.invDir = 1.0 / dir;
    return ray;
}

struct TriHit {
    float t, u, v;
};

struct Hit {
    uint id;
    float t, u, v;
};

float intersect(BBox bbox, Ray ray) {
    vec3 tmin = (bbox.min.xyz - ray.pos) * ray.invDir;
    vec3 tmax = (bbox.max.xyz - ray.pos) * ray.invDir;

    vec3 t1 = min(tmin, tmax);
    vec3 t2 = max(tmin, tmax);

    float tNear = max(max(t1.x, t1.y), t1.z);
    float tFar  = min(min(t2.x, t2.y), t2.z);

    if (tFar >= max(tNear, ray.tmin) && tNear < ray.tmax)
        return tNear;
    return -1.0;
}

TriHit intersect(uint id, Ray ray, float eps) {
    PrecomputedTriangle tri = triangleBuffer.data[id];
    vec3 p0 = tri.p0.xyz;
    vec3 e1 = tri.e1.xyz;
    vec3 e2 = tri.e2.xyz;
    vec3 N = tri.N.xyz;

    vec3 c = p0 - ray.pos;
    vec3 r = cross(ray.dir, c);
    float inv_det = 1.0 / dot(N, ray.dir);

    float u = dot(r, e2) * inv_det;
    float v = dot(r, e1) * inv_det;
    float w = 1.0 - u - v;

    if (u >= eps && v >= eps && w >= eps) {
        float t = dot(N, c) * inv_det;
        if (t >= ray.tmin && t <= ray.tmax)
        return TriHit(t, u, v);
    }

    return TriHit(-1, 0, 0);
}

bool isLeaf(Node node) {
    return primCount(node.index) != 0;
}

Hit intersect(Ray ray, float eps) {
    Hit closestHit = Hit(-1, 0, 0, 0);
    float closestT = 1e30;
    uint stack[32];
    uint sp = 0;
    stack[sp++] = 0;
    while (sp != 0) {
        uint nodeIdx = stack[--sp];
        Node node = nodeBuffer.data[nodeIdx];
        float tNode = intersect(node.bbox, ray);
        if (tNode == -1.0 || tNode >= closestT) continue;
        uint primCount = primCount(node.index);
        if (primCount != 0) {
            uint id = id(node.index);
            for (uint i = 0; i < primCount; ++i) {
                TriHit triHit = intersect(id + i, ray, eps);
                if (triHit.t > eps && triHit.t < closestT) {
                    closestT = triHit.t;
                    closestHit = Hit(id + i, triHit.t, triHit.u, triHit.v);
                }
            }
        } else {
            uint leftIdx  = id(node.index);
            uint rightIdx = leftIdx + 1;
            Node left  = nodeBuffer.data[leftIdx];
            Node right = nodeBuffer.data[rightIdx];
            float tLeft  = intersect(left.bbox, ray);
            float tRight = intersect(right.bbox, ray);
            bool hitLeft  = (tLeft  != -1.0) && (tLeft  < closestT);
            bool hitRight = (tRight != -1.0) && (tRight < closestT);
            if (hitLeft && hitRight) {
                if (tLeft < tRight) {
                    stack[sp++] = rightIdx;
                    stack[sp++] = leftIdx;
                } else {
                    stack[sp++] = leftIdx;
                    stack[sp++] = rightIdx;
                }
            } else if (hitLeft) {
                stack[sp++] = leftIdx;
            } else if (hitRight) {
                stack[sp++] = rightIdx;
            }
            //            uint leftIdx  = id(node.index);
            //            uint rightIdx = leftIdx + 1;
            //
            //            float tLeft  = -1.0;
            //            float tRight = -1.0;
            //
            //            Node left  = nodeBuffer.data[leftIdx];
            //            tLeft = intersect(left.bbox, ray);
            //
            //            if (tLeft != -1.0 && tLeft < closestT) {
            //                stack[sp++] = leftIdx;
            //            }
            //
            //            Node right = nodeBuffer.data[rightIdx];
            //            tRight = intersect(right.bbox, ray);
            //
            //            if (tRight != -1.0 && tRight < closestT) {
            //                stack[sp++] = rightIdx;
            //            }
        }
    }

    return closestHit;
}
vec2 getUV(uint id, float u, float v) {
    const float w = 1.0 - u - v;
    return u * triangleExtraBuffer.data[id].uv1 +
    v * triangleExtraBuffer.data[id].uv2 +
    w * triangleExtraBuffer.data[id].uv0;
}

vec3 traceRay(Ray ray) {
    Hit hit = intersect(ray, 1e-6);
    if (hit.id == -1) return vec3(0.0);
    vec2 uv = getUV(hit.id, hit.u, hit.v);
    vec3 texColor = texture(textures[nonuniformEXT(materialIndexBuffer.data[hit.id] * TEXTURE_NUM)], uv).rgb;
    return texColor;
}

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    const float imagePlaneHeight = 2.0 * tan(radians(camera.FOV * 0.5));
    const float imagePlaneWidth  = imagePlaneHeight * camera.aspectRatio;

    const float u  = (coord.x + 0.5) / pc.width;
    const float px = (2.0 * u - 1.0) * imagePlaneWidth * 0.5;
    const float v  = (coord.y + 0.5) / pc.height;
    const float py = (2.0 * v - 1.0) * imagePlaneHeight * 0.5;
    vec3 dir = normalize(px * vec3(camera.right) + py * vec3(camera.up) + vec3(camera.forward));
    Ray ray = makeRay(vec3(camera.position), dir, camera.nearPlane, camera.farPlane);
    vec3 color = traceRay(ray);
    imageStore(outImage, coord, vec4(color, 1.0));
}
